/*
 * =====================================================================================
 *
 *       Filename:  main.c
 *
 *    Description:  自动生成 Makefile 的程序
 *
 *        Version:  1.0
 *        Created:  2010年09月01日 09时56分28秒
 *       Revision:  none
 *       Compiler:  gcc
 *
 *         Author:  黄电春 (HDC), pbe_sedm@126.com
 *        Company:  HDC
 *
 * =====================================================================================
 */
#include <stdio.h>
#include <time.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <unistd.h>
#include <string.h>
#include <dirent.h>

#define MAKEFILE_NAME 	"Makefile"

void generate_time(char *, size_t maxsize);
void generate_header(int fd);
void generate_options(int fd);
void generate_output_directory(int fd);
void generate_rules(int fd);
void generate_build_rules(int fd);

int main(int argc, char *argv[])
{
	int fd;

	if( (fd = open(MAKEFILE_NAME, O_WRONLY | O_CREAT | O_TRUNC)) == -1)
		return -1;

	generate_header(fd);
	generate_options(fd);
	generate_output_directory(fd);
	generate_rules(fd);
	generate_build_rules(fd);

	chmod(MAKEFILE_NAME, S_IRUSR | S_IWUSR | S_IXUSR);

	close(fd);

	return 0;
}

void generate_time(char * dt, size_t maxsize)
{
	time_t now;
	struct tm *tm_now;
	
	time(&now);
	tm_now = localtime(&now);
	strftime(dt, maxsize, "%Y-%m-%d %H:%M:%S zone: %Z%n", tm_now);
}

void generate_header(int fd)
{
	char cwd[80];
	char datetime[30];
	char line[] = "#############################################################################";
	
	write(fd, line, strlen(line));

	getcwd(cwd, sizeof(cwd));
	char *p = rindex(cwd, '/') + 1;
	
	strcpy(line, "\n# Makefile for building: ");
	strcat(line, p);
	write(fd, line, strlen(line));

	strcpy(line, "\n# Generated by hkfile (0.0.1) (gcc 4.4.3) on: ");
	generate_time(datetime, 30);
	strcat(line, datetime);
	write(fd, line, strlen(line));

	strcpy(line, "\n# Project: ");
	strcat(line, p);
	write(fd, line, strlen(line));

	strcpy(line, "\n# Template: app");
	write(fd, line, strlen(line));

	strcpy(line, "\n#############################################################################");
	write(fd, line, strlen(line));
}

void generate_options(int fd)
{
	char line[200];

	strcpy(line, "\n\n####### Compiler, tools and options\n\n");
	write(fd, line, strlen(line));

	strcpy(line, "CC\t\t\t\t= gcc\n");
	strcat(line, "CXX\t\t\t\t= g++\n");
	strcat(line, "DEFINES\t\t\t= \n");
	strcat(line, "FLAGS\t\t\t= -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)\n");

	write(fd, line, strlen(line));

	strcpy(line, "CXXFLAGS\t\t= -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)\n");
	write(fd, line, strlen(line));

	strcpy(line, "INCPATH\t\t\t= -I.\n");
	strcat(line, "LINK\t\t\t= g++\nLIBS\t\t\t= $(SUBLIBS)\n");
	strcat(line, "AR\t\t\t\t= ar cqs\n");
	write(fd, line, strlen(line));

	strcpy(line, "TAR\t\t\t\t= tar -cf\n");
	strcat(line, "COMPRESS\t\t= gzip -9f\n");
	strcat(line, "COPY\t\t\t= cp -f\n");
	strcat(line, "COPY_FILE\t\t= $(COPY)\n");
	strcat(line, "COPY_DIR\t\t= $(COPY) -r\n");
	strcat(line, "STRIP\t\t\t= strip\n");
	write(fd, line, strlen(line));
				  
	strcpy(line, "INSTALL_FILE\t= install -m 644 -p\n");
	strcat(line, "INSTALL_DIR\t\t= $(COPY_DIR)\n");
	strcat(line, "INSTALL_PROGRAM\t= install -m 755 -p\n");
	write(fd, line, strlen(line));

	strcpy(line, "DEL_FILE\t\t= rm -f\n");
	strcat(line, "SYNLINK\t\t\t= ln -f -s\n");
	strcat(line, "DEL_DIR\t\t\t= rmdir\n");
	strcat(line, "MOVE\t\t\t= mv -f\n");
	strcat(line, "CHK_DIR_EXISTS\t= test -d\n");
	strcat(line, "MKDIR\t\t\t= mkdir -p\n");
	write(fd, line, strlen(line));
}

void generate_output_directory(int fd)
{
	char line[256];

	strcpy(line, "\n####### Output directory\n\n");
	strcat(line, "OBJECTS_DIR\t\t= ./\n\n");
	strcat(line, "###### Files\n\n");
	write(fd, line, strlen(line));

	//strcpy(line, "SOURCES\t\t\t= $(wildcard *.c *.cpp)\n");
	//strcat(line, "OBJECTS\t\t\t= $(patsubst %.c,%.o, $(patsubst %.cpp,%.o, $(SOURCES)))\n");

	strcpy(line, "SOURCES\t\t\t= ");
	write(fd, line, strlen(line));

	struct dirent **namelist;
	char cwd[256];
	int i;
	int total;
	int valid_total = 0;
	
	getcwd(cwd, 256);
	total = scandir(cwd, &namelist, 0, alphasort);

	if (total > 0)
	{
		for( i = 0 ; i < total ; ++i )
		{
			if( strstr(namelist[i]->d_name, ".c") != 0 || strstr(namelist[i]->d_name, ".cpp") != 0)
			{
				strcpy(line, (1 == valid_total ? " \\\n\t\t\t\t  " : ""));
				strcat(line, namelist[i]->d_name);
				write(fd, line, strlen(line));
				valid_total = 1;
			}
		}
	}
	
	strcpy(line, "\nOBJECTS\t\t\t= ");
	write(fd, line, strlen(line));
	valid_total = 0;

	if( total > 0 )
	{
		for( i = 0 ; i < total ; ++i )
		{
			if( strstr(namelist[i]->d_name, ".c") != 0 || strstr(namelist[i]->d_name, ".cpp") != 0 )
			{
				strcpy(line, (1 == valid_total ? " \\\n\t\t\t\t  " : ""));
				strcat(line, namelist[i]->d_name);
				char *p = strstr(line, ".c");
				strcpy(p, ".o\0");
				write(fd, line, strlen(line));
				valid_total = 1;
			}
		}		
	}
}

void generate_rules(int fd)
{
	char line[256];
	char cwd[256];

	getcwd(cwd, sizeof(cwd));
	char *p = rindex(cwd, '/') + 1;
	
	strcpy(line, "\nTARGET\t\t\t= ");
	strcat(line, p);
	
	write(fd, line, strlen(line));

	strcpy(line, "\n\nfirst: all\n\n");
	strcat(line, "######### Implicit rules\n\n");
	strcat(line, ".SUFFIXES: .o .c .cpp .cc .cxx .C\n\n");
	write(fd, line, strlen(line));

	strcpy(line, ".cpp.o:\n");
	strcat(line, "\t$(CXX) -c $(CXXFLAGS) $(INCPATH) -o \"$@\" \"$<\"\n\n");
	write(fd, line, strlen(line));

	strcpy(line, ".cc.o:\n");
	strcat(line, "\t$(CXX) -c $(CXXFLAGS) $(INCPATH) -o \"$@\" \"$<\"\n\n");
	write(fd, line, strlen(line));

	strcpy(line, ".cxx.o:\n");
	strcat(line, "\t$(CXX) -c $(CXXFLAGS) $(INCPATH) -o \"$@\" \"$<\"\n\n");
	write(fd, line, strlen(line));

	strcpy(line, ".C.o:\n");
	strcat(line, "\t$(CXX) -c $(CXXFLAGS) $(INCPATH) -o \"$@\" \"$<\"\n\n");
	write(fd, line, strlen(line));

	strcpy(line, ".c.o:\n");
	strcat(line, "\t$(CC) -c $(CFLAGS) $(INCPATH) -o \"$@\" \"$<\"\n\n");
	write(fd, line, strlen(line));
}

void generate_build_rules(int fd)
{
	char line[256];
	strcpy(line, "######## Build rules\n\n");
	strcat(line, "all: Makefile $(TARGET)\n\n");
	write(fd, line, strlen(line));

	strcpy(line, "$(TARGET): $(OBJECTS)\n\t$(LINK) $(CFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS)\n\n");
	write(fd, line, strlen(line));

	strcpy(line, "clean:\n\t-$(DEL_FILE) $(OBJECTS)");
	write(fd, line, strlen(line));
}
