#############################################################################
# Makefile for building: mkfile
# Generated by hkfile (0.0.1) (gcc 4.4.3) on: 2012-10-17 18:00:43 zone: CST
# Project: mkfile
# Template: app
#############################################################################

####### Compiler, tools and options

CC				= gcc
CXX				= g++
DEFINES			= 
FLAGS			= -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS		= -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH			= -I.
LINK			= g++
LIBS			= $(SUBLIBS)
AR				= ar cqs
TAR				= tar -cf
COMPRESS		= gzip -9f
COPY			= cp -f
COPY_FILE		= $(COPY)
COPY_DIR		= $(COPY) -r
STRIP			= strip
INSTALL_FILE	= install -m 644 -p
INSTALL_DIR		= $(COPY_DIR)
INSTALL_PROGRAM	= install -m 755 -p
DEL_FILE		= rm -f
SYNLINK			= ln -f -s
DEL_DIR			= rmdir
MOVE			= mv -f
CHK_DIR_EXISTS	= test -d
MKDIR			= mkdir -p

####### Output directory

OBJECTS_DIR		= ./

###### Files

SOURCES			= main.c
OBJECTS			= main.o
TARGET			= mkfile

first: all

######### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

######## Build rules

all: Makefile $(TARGET)

$(TARGET): $(OBJECTS)
	$(LINK) $(CFLAGS) -o $(TARGET) $(OBJECTS) $(LIBS)

clean:
	-$(DEL_FILE) $(OBJECTS)